### ISSUE TITLE
queryRenderedFeatures freezes the app when the app is in the background

### ISSUE THREAD

**Issue by csimpi** [mapbox/mapbox-gl-native-android#423] opened 2020-06-06 20:57 UTC
Hi, I'm having a very strange issue with `queryRenderedFeatures`.
When I call it first after map rendered, I can get the desired features, works perfectly.

I want to get the features of the viewport during I'm moving. So when there's a significant position change, I check if the new position is within the current viewport or my position is outside of the viewport.

If I'm outside, I move the map, make my position the center of the viewport, then I would like to get the features of the new viewport I call `queryRenderedFeatures` and it makes the app hang forever.
No response, the app is frozen.

Wrapping this part to try-catch I'm getting the same, freeze, no catch.
Wrapping this to setTimeout for 3000 ms (to wait for everything is rendered), the same result.

It seems this happens when the app is in the background: I use a GPS mocking app which simulates that I'm walking.

When I start my App, then switch to the GPS mocking app, push start (so my app is in the background) `queryRenderedFeatures ` freezes the app for good.

When I start the GPS mocking simulation first then I start my app `queryRenderedFeatures ` won't freeze it, it works, I guess because my app is in the foreground. 

It seems `queryRenderedFeatures` won't work when the app is in the background. Am I right? It's a bit odd I can't tell what's on the map when it's in the background, I wanted to tell which polygon I'm standing in even if the app is in the background. I want to send a notification to the user when they're within a polygon.

**Comment by Chaoba** [comment] 2020-06-08 03:44
Hey @csimpi , thanks for using Mapbox. Unfortunately, `queryRenderFeautures` will not work in background as `renderThread` will be paused.

That said, this is not a support forum, but a place for bug reports and feature requests. Feel free to checkout the [Documentation](https://docs.mapbox.com/android/maps/overview/), reach out to [Support](https://support.mapbox.com/hc/en-us) or [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) community.

**Comment by csimpi** [comment] 2020-06-08 09:27
@Chaoba Why is this closed? This is a BUG, case it freezes the App! It shouldn't make the app hang even if it's wrapped with try/catch. Very rude behavior here all the time ....

**Comment by Chaoba** [comment] 2020-06-08 10:21
@csimpi I closed this issue as `queryRenderFeautures` is not supported while app is in background. But you are right, it should not cause ANR. Reopen this issue and we will try to fix this ANR.

**Comment by Chaoba** [comment] 2020-06-09 08:27
@csimpi I’m not able to reproduce this issue, would you mind to create a minimal project that could reproduce it and share it to me? Thanks.

**Comment by Chaoba** [comment] 2020-06-29 02:07
@csimpi I will close this issue as I still can't reproduce it locally, feel free to reopen if you got the specific way to reproduce it.

**Closed by Chaoba** 2020-06-29 02:07 UTC
