### ISSUE TITLE
[Android] Double tapping while tracking zooms to location, not puck

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-gl-native-android#44] opened 2019-10-07 07:34 UTC
Double tapping the map while tracking the user causes the camera to zoom to the tapped location, while the camera mode is still "tracking" the user's puck. This behavior will look weird for the user, since it won't look like the puck is still being tracked (although, at location updates, the camera will start actually tracking again).

In previous versions (I'm afraid I don't know the exact versions) the camera would zoom in on the user's puck if the camera was tracking, regardless of where on the map was double tapped.

The zoom behavior seems to work as expected when the user is getting location updates and on the move, and so is likely mostly a problem while standing still.

### Steps to reproduce

 1. Have an idle location
 2. Set camera mode to `CameraMode.TRACKING_GPS_NORTH` or `CameraMode.TRACKING_GPS`
 3. Double tap on the map, somewhere that is not on the user's location

### Expected behavior
The map would zoom in on the user's puck, and the camera would still be tracking the user.

### Actual behavior
The map zooms in on the chosen location, and it looks like the puck is no longer being tracked, even though it is.

I have noticed sometimes that the zoom behavior works correctly when starting up the app, but after moving the map (setting camera mode to non-tracking) and setting camera mode to Tracking again, the issue reappears.

### Configuration

**Mapbox SDK versions:** 8.4.0

**Comment by Chaoba** [comment] 2020-05-06 02:37
@cmahopper If you register `OnCameraTrackingChangedListener`, when user standstill for a while,  you will find camera tracking mode changes to `CameraMode.NONE`. I believe this is why it will not track user location while zoom in. @LukasPaczos please fix me if I'm wrong.

**Comment by LukasPaczos** [comment] 2020-05-06 09:28
Now that I look at this, I think it's an issue with the focal point. When the puck is moving, we have a better chance of updating the focal point of the gesture and get it to be fixed on the puck because the invalidation happens only when the location value is updated. If we're not moving, we will not invalidate the focal point.

I think the solution is trying to invalidate the focal point in the tracking mode whenever camera position changes, not only when the new location is available (see `LocationCameraController` impl). This might be slightly more expensive computationally (because of the JNI passes), but in the end, it should resolve the issue.

**Comment by Chaoba** [comment] 2020-05-08 05:41
Not able to reproduce this issue on 9.2.0
![ezgif com-resize](https://user-images.githubusercontent.com/8577318/81368370-30b05700-9122-11ea-8869-db6eab1b0ea2.gif)

**Comment by LukasPaczos** [comment] 2020-05-08 09:09
What about this quick jump of the camera up and down? I think that might be exactly the same issue. The focal point is above the puck, so the zoom animation shoots higher than it should. Later the camera moves back on top of the puck with a location animation.

**Closed** 2020-05-27 09:56 UTC
