### ISSUE TITLE
MapBox crashing with x86 issues

### ISSUE THREAD

**Issue by dan-0** [mapbox/mapbox-gl-native-android#320] opened 2020-04-10 17:16 UTC
We're seeing crashes that appear to be related to x86 issues.

Stacktrace:
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
     FATAL EXCEPTION: main
Process: com.crash.mapboxcrash, PID: 7496
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
	at com.crash.mapboxcrash.MainActivity.onCreate(MainActivity.kt:14)
	at android.app.Activity.performCreate(Activity.java:6975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Gradle config / Mapbox Version:
```
        implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
```

Currently, we're only able to replicate using Firebase Test Lab. To replicate the issue:
1. Create a new Android Project with a MainActivity
2. Import the above Mapbox dependencies in gradle.
3. Initialize Mapbox via `Mapbox.getInstance(this, MAPBOX_TOKEN)` in MainActivity
4. Build a signed debug APK
5. Upload the APK to Firebase Test Lab doing a "Robo" test using the Nexus 5x _virtual device_ on SDK 26 (also replicable with valid Instrumentation tests)
6. After running you will see the crash with the provided stacktrace.

We were able to isolate the issue based on this comment: https://github.com/mapbox/mapbox-gl-native/issues/14428#issuecomment-585883399

The proposed solution of adding this did **not** work:
```
defaultConfig {
       ...
       ndk {
           abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
       }
}
```

However, explicitly specifying the following configuration does work (note: we can't do this for production, so the above comment's solution is not viable in our case)
```
defaultConfig {
       ...
       ndk {
           abiFilters "x86"
       }
}
```

We've tested this against the following versions:
`com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0`
`com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0`

We've had no issues with our x86 emulators when running locally so we're assuming this is some form of odd device configuration issue.

**Comment by reline** [comment] 2020-04-16 19:53
Possibly related to or a duplicate of #111

**Comment by tobrun** [comment] 2020-04-21 09:22
Thank you for reaching out and providing a lot of information to help reproduce. This indeed looks like a duplicate of #111, prioritizing this to be investigated in https://github.com/mapbox/mapbox-gl-native-android/issues/111#issuecomment-617061519. Thanks again for the report.

**Closed by tobrun** 2020-04-21 09:22 UTC

**Comment by tobrun** [comment] 2020-06-03 12:04
Following up on this in #416
